"""remove nullable=False from column username

Revision ID: 01d01ee9fc23
Revises: 7e7b31066f76
Create Date: 2025-05-30 13:31:33.594841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '01d01ee9fc23'
down_revision: Union[str, None] = '7e7b31066f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=False)
    # ### end Alembic commands ###
