"""remove lang column from User table

Revision ID: 7fb8900aa1b9
Revises: 01d01ee9fc23
Create Date: 2025-05-30 13:35:31.803140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fb8900aa1b9'
down_revision: Union[str, None] = '01d01ee9fc23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lang')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lang', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
